Seyu/Controllers/AdminController.cs
using HtmlAgilityPack;
using HtmlAgilityPack.CssSelectors.NetCore;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using Seyu.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.Intrinsics.Arm;
using System.Security.AccessControl;
using System.Security.Policy;
using System.Threading.Tasks;
namespace Seyu.Controllers
{
    public class AdminController : Controller
    {
        public string emails = "email@gmail.com";
        public string passwords = "password";
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string k)
        {
            string email = Request.Method == "POST" ? Request.Form["email"] : string.Empty;
            string password = Request.Method == "POST" ? Request.Form["password"] : string.Empty;
            if (emails == email && passwords == password)
            {
                return Redirect("../Admin/Edit");


            }
            return Redirect("");
        }
        [HttpGet]
        public IActionResult Edit()
        {


            var settings = MongoClientSettings.FromConnectionString("mongodb+srv://dbSeyu:q123q123q@cluster0.vaizm.mongodb.net/?retryWrites=true&w=majority");
            var client = new MongoClient(settings);
            var database = client.GetDatabase("seyuDb");
            var collection = database.GetCollection<Laptop>("computer");
            var Result = collection.Find(a => true).ToList();

            return View(Result);
        }
        [HttpPost]
        public IActionResult Edit(string submitButton)
        {
            switch (submitButton)
            {
                case "Search":
                    // delegate sending to another controller action
                    return (Search());
                case "WebScraping":
                    // call another action to perform the cancellation
                    return (Scrap());
                default:
                    // If they've submitted the form without a submitButton, 
                    // just return the view again.
                    return (View());
            }
        
          
        }
        private ActionResult Scrap()
        {
           DatabaseConnection.ClearData();
            WebScraping();
       DatabaseConnection.TrendyolConnect();
       DatabaseConnection.VatanConnect();
        DatabaseConnection.n11Connect();
       DatabaseConnection.mediaMarktConnect();



            return Redirect("../Admin/Edit");
           
        }
        private void WebScraping()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            HttpClient client = new HttpClient(clientHandler);

            //Start with a list of URLs
            var urls = new string[]
                {
        "https://www.vatanbilgisayar.com/notebook/",
         "https://www.vatanbilgisayar.com/laptop/?page=2",
          "https://www.vatanbilgisayar.com/laptop/?page=3",
           "https://www.vatanbilgisayar.com/laptop/?page=4",
            "https://www.vatanbilgisayar.com/laptop/?page=5",
        "https://www.n11.com/bilgisayar/dizustu-bilgisayar",
        "https://www.n11.com/bilgisayar/dizustu-bilgisayar?pg=2",
        "https://www.n11.com/bilgisayar/dizustu-bilgisayar?pg=3",
        "https://www.n11.com/bilgisayar/dizustu-bilgisayar?pg=4",
        "https://www.n11.com/bilgisayar/dizustu-bilgisayar?pg=5",
        "https://www.trendyol.com/laptop-x-c103108?pi=2",
        "https://www.trendyol.com/laptop-x-c103108?pi=3",
        "https://www.trendyol.com/laptop-x-c103108?pi=4",
        "https://www.trendyol.com/laptop-x-c103108?pi=5",
        "https://www.mediamarkt.com.tr/tr/category/_laptop-504926.html",
        "https://www.mediamarkt.com.tr/tr/category/_laptop-504926.html?searchParams=&sort=suggested&view=&page=2",
        "https://www.mediamarkt.com.tr/tr/category/_laptop-504926.html?searchParams=&sort=suggested&view=&page=3"
                };

            //Start requests for all of them
            var requests = urls.Select
                (
                    url => client.GetStringAsync(url)
                ).ToList();

            //Wait for all the requests to finish
            //  await Task.WhenAll(requests);

            //Get the responses
            var responses = requests.Select
                (
                    task => task.Result
                );
            //  await Task.WhenAll((Task)responses);
            var index = 0;
            foreach (var response in responses)
            {
            if (index >= 0 && index <=4)
                {
                    ParseHtmlVatan(response);

                }
              if (index >= 5 && index <=9)
                {
                    ParseHtmln11(response);
                }
              if (index >= 10 && index <=13)
                {
                    ParseHtmlTrendyol(response);
                }
             if (index >= 14)
                {
                    ParseHtmlMediaMarkt(response);
                }

                index++;

            }

        }
        private void ParseHtmlMediaMarkt(string html)
        {
            HtmlDocument htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(html);

            var programmerLinks = htmlDoc.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "product-wrapper")

    .Take(30)
    .ToList();

            var data = programmerLinks.Select((node) =>
            {
                return new
                {
                    baslik = node.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "content ").QuerySelectorAll("h2"),

                    marka = node.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "content "),

                    fiyat = node.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "price small"),

                    resim = node.QuerySelectorAll("span")
                  .Where(e => e.GetAttributeValue("class", "") == "photo clickable"),

                    url = node.QuerySelectorAll("span")
                  .Where(e => e.GetAttributeValue("class", "") == "photo clickable"),


                };
            }
                );
            // Marka , fiyat , resim , başlık , derece,url

            List<string> baslikListe = new List<string>();
            List<string> markaListe = new List<string>();
            List<double> fiyatListe = new List<double>();
            List<string> resimListe = new List<string>();
            List<string> urlListe = new List<string>();

            foreach (var link in data)
            {
                

                foreach (var baslik in link.baslik)
                {

                    baslikListe.Add(baslik.InnerText);
                }

                foreach (var marka in link.marka)
                {
                    markaListe.Add(marka.InnerText.Replace("\n", "").Replace("\t", "").Split(" ")[0]);
                }
                foreach (var fiyat in link.fiyat)
                {
                    double switched = double.Parse(fiyat.InnerText.Replace(".", "").Replace("TL", "").Replace("-", "").Replace(",", "."));
                    fiyatListe.Add(switched);
                }

                foreach (var resim in link.resim)
                {
                   
                        resimListe.Add("https://cdn.dsmcdn.com//ty513/product/media/images/20220822/16/163937942/117736341/1/1_org.jpg");
                }

                foreach (var url in link.url)
                {
                    urlListe.Add(url.GetAttributeValue("data-clickable-href", ""));
                }

            }
            for (int i = 0; i < baslikListe.Count; i++)
            {
                Laptop laptop = new Laptop
                {
                    Marka = markaListe[i],
                    Fiyat = fiyatListe[i],
                    Resim = resimListe[i],
                    Baslik = baslikListe[i],
                    Url = "https://www.mediamarkt.com.tr"+ urlListe[i],
                    islemciMarkası = "  ",
                    islemciNesli = "  ",
                    islemciTeknolojisi = " ",
                    ram = " ",
                    ekranBoyutu = " ",
                    ekranKartı = "  ",
                    diskKapasitesi = "  ",

                };
                DatabaseConnection.mediaMarktLaptops.Add(laptop);


            }
            DetailMediaMarkt();

        }
        private void ParseHtmlVatan(string html)
        {
            HtmlDocument htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(html);

            var programmerLinks = htmlDoc.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "product-list product-list--list-page")

    .Take(30)
    .ToList();

            var data = programmerLinks.Select((node) =>
            {
                return new
                {
                    baslik = node.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "product-list__product-name"),

                    marka = node.QuerySelectorAll("div")
                  .Where(e => e.GetAttributeValue("class", "") == "product-list__product-name"),

                    fiyat = node.QuerySelectorAll("span")
                  .Where(e => e.GetAttributeValue("class", "") == "product-list__price"),

                    resim = node.QuerySelectorAll("img")
                  .Where(e => e.GetAttributeValue("class", "") == "lazyimg"),

                    url = node.QuerySelectorAll("a")

Seyu/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using Seyu.Models;

namespace Seyu.Controllers
{
    public class DetailController : Controller
    {
        public IActionResult Index(string baslik)
        {
            var settings = MongoClientSettings.FromConnectionString("mongodb+srv://dbSeyu:q123q123q@cluster0.vaizm.mongodb.net/?retryWrites=true&w=majority");
            var client = new MongoClient(settings);
            var database = client.GetDatabase("seyuDb");
            var collection = database.GetCollection<Laptop>("computer");
            var Result = collection.Find(a=> a.Baslik==baslik).FirstOrDefault();


            return View(Result);
           
        }
    }
}

Seyu/Views/Admin/Add.cshtml
@using (Html.BeginForm("Add", "Admin", FormMethod.Post))
{
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>
    <div>
        <!-- Left section of signup form -->
        <dive>
            <h1 class="text-center">Add Laptop</h1>
            <br />
            <form class="text-center" cl action="" method="post">
                <div class="mb-4">
                    <p>
                        <label for="Marka" class="form-label">Marka</label>
                            <input type="text" class="form-control" name="marka" id="Marka">
                </div>
                <div>
                    <p>
                        <label for="Model" class="form-label">Model</label>
                            <input type="text" class="form-control" name="model" id="Model">
                </div>
                <div>
                    <p>
                        <label for="Fiyat" class="form-label">Fiyat</label>
                            <input type="text" class="form-control" name="fiyat" id="username">
                </div>
                <div>
                    <p>
                        <label for="Baslik" class="form-label">Baslik</label>
                            <input type="text" class="form-control" name="baslik" id="Baslik">
                </div>
                <div>
                    <p>
                        <label for="Url" class="form-label"> URL </label>
                            <input type="text" class="form-control" name="url" id="Url">
                </div>
                <div>
                    <p>
                        <label for="IslemciMarkasi" class="form-label">İşlemci Markasi</label>
                        <input type="text" class="form-control" name="islemciMarkasi" id="IMArka">
                </div>
                <div>
                    <p>
                        <label for="IslemciNesli" class="form-label">İşlemci Nesli</label>
                            <input type="text" class="form-control" name="islemciNesli" id="INesil">
                </div>
                <div>
                    <p>
                        <label for="IslemciTeknolojisi" class="form-label">İşlemci Teknolojisi</label>
                        <input type="text" class="form-control" name="islemciTeknolojisi" id="Iteknoloji">
                </div>
                <div>
                    <p>
                        <label for="Ram" class="form-label">Ram</label>
                            <input type="text" class="form-control" name="ram"  id="Ram">
                </div>
                <div>
                    <p>
                        <label for="EkranBoyutu" class="form-label">Ekran Boyutu</label>
                            <input type="text" class="form-control" name="ekranBoyutu" id="Eboyutu">
                </div>
                <div>
                    <p>
                        <label for="EkranKartı" class="form-label">Ekran Kartı</label>
                            <input type="text" class="form-control" name="ekranKartı" id="Ekartı">
                </div>
                <div>
                    <p>
                        <label for="Disk" class="form-label">Disk Kapasitesi</label>
                            <input type="text" class="form-control" name="diskKapasitesi" id="Disk">
                </div>
                  
                    <button class="btn btn active" href='@Url.Action("Add", "Admin", new { k = "" })' data-form-method="post">    Add </button>

            </form>

    </div>



</body>
</html>
}

Seyu/Views/Admin/Edit.cshtml
@model List<Laptop>
@using (Html.BeginForm("Edit", "Admin", FormMethod.Post))
{



    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - SeYu</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <style>
            .flexbox-container {
                display: flex;
                /*align-items:center;*/
                align-items: stretch;
            }

            .box-1 {
                width: 280px;
            }

            .box-2 {
                width: max-content;
                flex-grow: 1;
            }
        </style>



    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href='@Url.Action("Index", "Home")'>Seyu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form method="post" class="d-flex position-absolute top-50 start-50 translate-middle" role="search">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit" name="submitButton" value="Search">Search</button>
                    </form>
                  
                </div>
            </div>
        </nav>
        <div class="flexbox-container">
            <div class="flexbox-item box-1 d-flex flex-column flex-shrink-0 p-3 bg-light">
                <form method="post">
                    <ul class="nav nav-pills flex-column mb-auto">
                     
                        <hr>
                        <li class="text-center">

                           
                            <a class="btn btn active"  href='@Url.Action("Add", "Admin")'>Add Computer</a>
                        </li>
                        <br />
                        <li class="text-center">
                            <!-- web scrabing butonu burda-->
                            <button class="btn btn active" type="submit" name="submitButton" value="WebScraping">Web Scrabing</button>
                           
                        </li>

                    </ul>
                </form>
            </div>
            <div class="flexbox-item box-2" style="width:1500px;">
                <ul class="nav nav-pills flex-column mb-auto">
                    @foreach (var item in Model)
                    {
                        <li>
                            <div class="card mb-3">
                                <div class="row g-0">
                                    <div class="col-md-4">


                                        <img src="@item.Resim" class="img-fluid rounded-start" alt="...">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h2>@item.Marka</h2>
                                            <a class="card-title" href='@Url.Action("Index", "Detail", new { baslik = item.Baslik })'>@item.Baslik </a>
                                            <!-- CSS only   <a class="card-title" asp-area="" asp-controller="Detail" asp-action="Index">@item.Baslik</a>-->
                                            <p class="card-text" style="color:limegreen" :">@item.Fiyat TL</p>

                                            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                                                <div class="btn-group me-2" role="group" aria-label="First group">
                                                    @{
                                                        if (item.Url.Contains("trendyol"))
                                                        {
                                                            <a type="button" href="@item.Url" class="btn active" style="color:orange">Trendyol</a>
                                                        }
                                                        else
                                                        {
                                                            <a type="button" href="#" class="btn active" style="color:orange">Trendyol</a>
                                                        }
                                                    }

                                                   

                                                </div>
                                                <div class="btn-group me-2" role="group" aria-label="Second group">
                                                    @{
                                                        if (item.Url.Contains("n11"))
                                                        {
                                                            <a type="button" href="@item.Url" class="btn active" style="color:red">n11</a>

                                                        }
                                                        else
                                                        {
                                                            <a type="button" href="#" class="btn active" style="color:red">n11</a>

                                                        }
                                                    }

                                                </div>
                                                <div class="btn-group" role="group" aria-label="Third group">
                                                    @{
                                                        if (item.Url.Contains("vatan"))
                                                        {
                                                            <a type="button" href="@item.Url" class="btn active" style="color:blue">Vatan</a>


                                                        }
                                                        else
                                                        {
                                                            <a type="button" href="#" class="btn active" style="color:blue">Vatan</a>

                                                        }
                                                    }
                                                </div>
                                                <div class="btn-group" role="group" aria-label="Fourth group">
                                                    @{
                                                        if (item.Url.Contains("mediamarkt"))
                                                        {
                                                            <a type="button" href="@item.Url" class="btn active" style="color:deeppink">Media Markt</a>


                                                        }
                                                        else
                                                        {
                                                            <a type="button" href="#" class="btn active" style="color: deeppink">Media Markt</a>

                                                        }
                                                    }

                                                </div>
                                            </div>
                                            <br>
                                            <br>
                                            <div class="btn-toolbar" role="toolbar">
                                                <div class="btn-group me-2" role="group" aria-label="First group">

                                                    <a  class="btn active" style="color:darkred" href='@Url.Action("Sil", "Admin", new { baslik = item.Baslik })'>Sil</a>
                                                   

                                                </div>
                                                <div class="btn-group me-2" role="group">
                                                    <a class="btn active" style="color:green" href='@Url.Action("Update", "Admin", new { id = item.Id , bos="" })'>Güncelle</a>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }


            </div>
        </div>
    </body>

    </html>


}

Seyu/Views/Admin/Index.cshtml
@using (Html.BeginForm("Index", "Admin", FormMethod.Post))
{
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>

    </style>

</head>
<body>
    <h1 class="text-center " style="background-color:aliceblue">SeYu </h1>
    <section class="w-100 p-4 d-flex justify-content-center pb-4">
        <form method="post" style="width: 22rem;">
            <!-- Email input -->
            <div class="form-outline mb-4">  
                 <input type="email" name="email" id="form2Example1" class="form-control"> 
                <label class="form-label" for="form2Example1" style="margin-left: 0px;">Email address</label>
                <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 88.8px;"></div><div class="form-notch-trailing"></div></div>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                
                   <input type="password" name="password" id="form2Example2" class="form-control">
                <label class="form-label" for="form2Example2" style="margin-left: 0px;">Password</label>
                <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 64.8px;"></div><div class="form-notch-trailing"></div></div>
            </div>

            <!-- Submit button -->
                <button class=""id="btn-login">Giriş</button>

        </form>
    </section>
</body>
</html>
}

Seyu/Views/Admin/Update.cshtml
@model Laptop
@using (Html.BeginForm("Update", "Admin", FormMethod.Post))
{
    <html lang="en">
    <head>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    </head>
    <body>
        <div>
            <!-- Left section of signup form -->
            <dive>
                <h1 class="text-center">Update Laptop</h1>
                <br />
                <form class="text-center" cl action="" method="post">
                    <div class="mb-4">
                        <p>
                            <label for="Marka" class="form-label">Marka</label>
                            <input type="text" class="form-control" name="marka" id="Marka" value=@Model.Marka>
                    </div>
                    <div >
                        <p>
                            <label for="ID" class="form-label">ID</label>
                            <input type="text" class="form-control" name="id" id="id" value=@Model.Id disabled readonly>
                    </div>
                    <div>
                        <p>
                            <label for="Model" class="form-label">Model</label>
                            <input type="text" class="form-control" name="model" id="Model" >
                    </div>
                    <div>
                        <p>
                            <label for="Fiyat" class="form-label">Fiyat</label>
                            <input type="text" class="form-control" name="fiyat" id="username" value=@Model.Fiyat>
                    </div>
                    <div>
                        <p>
                            <label for="Baslik" class="form-label">Baslik</label>
                            <input type="text" class="form-control" name="baslik" id="Baslik" value=@Model.Baslik>
                    </div>
                    <div>
                        <p>
                            <label for="Url" class="form-label"> URL </label>
                            <input type="text" class="form-control" name="url" id="Url" value=@Model.Url>
                    </div>
                    <div>
                        <p>
                            <label for="IslemciMarkasi" class="form-label">İşlemci Markasi</label>
                            <input type="text" class="form-control" name="islemciMarkasi" id="IMArka" value=@Model.islemciMarkası>
                    </div>
                    <div>
                        <p>
                            <label for="IslemciNesli" class="form-label">İşlemci Nesli</label>
                            <input type="text" class="form-control" name="islemciNesli" id="INesil" value=@Model.islemciNesli>
                    </div>
                    <div>
                        <p>
                            <label for="IslemciTeknolojisi" class="form-label">İşlemci Teknolojisi</label>
                            <input type="text" class="form-control" name="islemciTeknolojisi" id="Iteknoloji" value=@Model.islemciTeknolojisi>
                    </div>
                    <div>
                        <p>
                            <label for="Ram" class="form-label">Ram</label>
                            <input type="text" class="form-control" name="ram" id="Ram" value=@Model.ram>
                    </div>
                    <div>
                        <p>
                            <label for="EkranBoyutu" class="form-label">Ekran Boyutu</label>
                            <input type="text" class="form-control" name="ekranBoyutu" id="Eboyutu" value=@Model.ekranBoyutu>
                    </div>
                    <div>
                        <p>
                            <label for="EkranKartı" class="form-label">Ekran Kartı</label>
                            <input type="text" class="form-control" name="ekranKartı" id="Ekartı" value=@Model.ekranKartı>
                    </div>
                    <div>
                        <p>
                            <label for="Disk" class="form-label">Disk Kapasitesi</label>
                            <input type="text" class="form-control" name="diskKapasitesi" id="Disk" value=@Model.diskKapasitesi>
                    </div>
                    <button class="btn btn active" href='@Url.Action("Update", "Admin", new { buton = "" })' data-form-method="post">    Update </button>
                   
                </form>

        </div>



    </body>
    </html>
}